---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/3/16 18:01
---
local debug = require("Phi").configuration.debug
if debug then
    require("mobdebug").start()
end