---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/3/20 10:15
---
do
    local phi = require("Phi")
    local debug = phi.configuration.debug
    if debug then
        local host = phi.configuration.debug_host
        local port = phi.configuration.debug_port
        require("mobdebug").start(host, port)
    end
end