---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Young.Z
--- DateTime: 2018/4/18 17:26
---
return {
    definition = {
        constructor_refs = "dataSource",
        order = 10,
        lrucache_size = 2000
    }
}