---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/3/29 9:37
---
local base_component = require "component.base_component"
local status = require "gateway.module.status"
local common = require "gateway.module.common"
local summary = require "gateway.module.summary"
local xpcall = xpcall

local mio_handler = base_component:extend()

function mio_handler:new()
    self.super:new("mio-statistics")
    self.order = -9999
    self.__definition = { type = "component" }
    return self
end

function mio_handler.init()
    ngx.log(ngx.ERR, "init===================================pid", ngx.worker.pid())
    ngx.log(ngx.ERR, "init===================================id", ngx.worker.id())
    xpcall(status.init, common.err_handle)
end

function mio_handler.init_worker()
    mio_handler.super:init_worker()
    ngx.log(ngx.ERR, "init worker-----------------------------------pid", ngx.worker.pid())
    ngx.log(ngx.ERR, "init worker-----------------------------------id", ngx.worker.id())
    xpcall(summary.sync_data_to_shared_dict, common.err_handle)
end

local function start(var, ctx)
    summary.log(var, ctx)
    status.log(var, ctx)
end

function mio_handler:log(var, ctx)
    mio_handler.super:log()
    xpcall(start, common.err_handle, var, ctx)
end

return mio_handler