---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/4/24 9:50
---
require("phi_debug")
local antMatcher = require "tools.ant_path_matcher"
local path = ngx.req.get_uri_args()["path"]
local patt = ngx.req.get_uri_args()["patt"]
if path and patt then
    ngx.say("path:[" .. path .. "]=====pattern:[" .. patt .. "]=====" .. tostring(antMatcher.match(patt, path)))
end